### ISSUE TITLE
Procedimento com Aplicações

### ISSUE THREAD

**Issue by leandro-repo** [eventick/pagseguro-transparente#19]
Que diferenças no processo poderiam ser implementadas para suportar o modelo de aplicações do PagSeguro?

**Comment by cirdes** [comment]
@leandro-repo, essa gem não suporta o modelo de aplicação do PagSeguro. O modelo de aplicação exige algumas etapas a mais que não foram implementadas. Como não conheço a fundo o modelo de aplicação não sei dizer quais mudanças seriam necessárias.

**Comment by leandro-repo** [comment]
Agradeço a resposta.
